/* eslint-disable */

/**
 *============================================================================
 * Config.gs — Default Configuration (Synced from GitHub)
 *============================================================================
 * This file contains the DEFAULT settings for the Gmail purge script.
 *
 * DO NOT edit this file directly in Google Apps Script — your changes
 * will be overwritten on the next sync from GitHub.
 *
 * To customize your settings, create a file called "UserConfig.gs" in the
 * same Apps Script project and override only the values you want to change.
 * UserConfig.gs is NEVER overwritten by the sync process.
 *============================================================================
 */

var DEFAULT_CONFIG = {
  // -----------------------------------------------------------------
  // GitHub auto-sync
  // -----------------------------------------------------------------

  githubRawUrl: 'https://raw.githubusercontent.com/zamarax/Public/main/Scripts/GoogleScripts/Google-Gmail-Clean-Up-Sent-Items.gs/Google-Gmail-Clean-Up-Sent-Items.gs',

  syncTrigger: {
    type: 'hours',
    value: 6
  },

  // -----------------------------------------------------------------
  // Deletion thresholds and filters
  // -----------------------------------------------------------------

  deleteAfterDays: 1825,

  maxDeletesPerRun: 50,

  dateRangeStart: null,
  dateRangeEnd: null,

  // -----------------------------------------------------------------
  // Search settings
  // -----------------------------------------------------------------

  targetLabel: 'in:sent',

  batchPageSize: 150,

  // -----------------------------------------------------------------
  // Summary email
  // -----------------------------------------------------------------

  sendSummaryEmail: true,

  summaryEmailTo: Session.getActiveUser().getEmail(),

  summaryEmailSubject: 'Gmail Clean-Up Report — Sent Items Purge',

  // -----------------------------------------------------------------
  // Dry-run / simulation mode
  // -----------------------------------------------------------------

  dryRun: false,

  // -----------------------------------------------------------------
  // Trigger settings
  // -----------------------------------------------------------------

  trigger: {
    type: 'days',
    value: 1,
    hour: 2,
    minute: 0
  },

  purgeMoreDelayMinutes: 2
}
